import os
from typing import Dict, Any, List
from fpdf import FPDF
from datetime import datetime

class ArchonReporter:
    def __init__(self):
        self.emerald_color = (16, 185, 129)
        self.dark_bg = (5, 7, 10)
        self.text_color = (203, 213, 225)

    def to_markdown(self, repo_data: Dict[str, Any]) -> str:
        """Generate a structured Markdown report."""
        name = repo_data.get("url", "").split("/")[-1] or "Repository"
        score = repo_data.get("overall_score", 0)
        label = repo_data.get("analysis_results", {}).get("maturity_label", "Unknown")
        ai = repo_data.get("analysis_results", {}).get("ai_analysis", {})
        
        md = f"# ArchonAI Architectural Audit: {name}\n"
        md += f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        md += f"**Maturity Score**: {score}/100 ({label} Grade)\n\n"
        
        md += "## Executive Summary\n"
        summary = ai.get("executive_summary", [])
        if isinstance(summary, list):
            md += "\n".join([f"{p}\n" for p in summary])
        else:
            md += f"{summary}\n"
        
        md += "\n## Neural Debt Audit\n"
        debt = ai.get("technical_debt", [])
        for item in debt:
            md += f"### {item.get('title', item.get('area', 'Issue'))}\n"
            md += f"**Impact**: {item.get('impact', 'N/A')}\n\n"
            md += f"{item.get('paragraph', item.get('issue', ''))}\n\n"
            
        md += "## Engineering Roadmap\n"
        roadmap = repo_data.get("analysis_results", {}).get("actionable_roadmap", [])
        for i, step in enumerate(roadmap):
            md += f"### Phase {i+1}: {step.get('title')}\n"
            md += f"{step.get('detail', step.get('description', ''))}\n\n"
            
        md += "## Tech Stack Matrix\n"
        notes = ai.get("tech_stack_notes", {})
        for tool, note in notes.items():
            md += f"- **{tool}**: {note}\n"
            
        md += "\n---\n*Generated by ArchonAI Intelligent Engine v1.1*"
        return md

    def to_pdf(self, repo_data: Dict[str, Any], output_path: str):
        """Generate a professionally styled PDF report."""
        pdf = FPDF()
        pdf.add_page()
        
        name = repo_data.get("url", "").split("/")[-1] or "Repository"
        score = repo_data.get("overall_score", 0)
        label = repo_data.get("analysis_results", {}).get("maturity_label", "Unknown")
        ai = repo_data.get("analysis_results", {}).get("ai_analysis", {})

        # Header
        pdf.set_fill_color(*self.emerald_color)
        pdf.rect(0, 0, 210, 40, 'F')
        
        pdf.set_font("helvetica", "B", 24)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 20, f"ARCHON AI AUDIT", ln=True, align='C')
        pdf.set_font("helvetica", "", 12)
        pdf.cell(0, 10, f"Project: {name} | Score: {score}/100", ln=True, align='C')
        
        pdf.ln(10)
        pdf.set_text_color(40, 40, 40)
        
        # Summary
        pdf.set_font("helvetica", "B", 16)
        pdf.set_text_color(*self.emerald_color)
        pdf.cell(0, 10, "EXECUTIVE SUMMARY", ln=True)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(60, 60, 60)
        
        summary = ai.get("executive_summary", [])
        if isinstance(summary, list):
            for para in summary:
                pdf.multi_cell(0, 5, para)
                pdf.ln(2)
        else:
            pdf.multi_cell(0, 5, str(summary))
            
        pdf.ln(5)
        
        # Technical Debt
        pdf.set_font("helvetica", "B", 16)
        pdf.set_text_color(*self.emerald_color)
        pdf.cell(0, 10, "NEURAL DEBT AUDIT", ln=True)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(60, 60, 60)
        
        debt = ai.get("technical_debt", [])
        for item in debt[:4]:
            pdf.set_font("helvetica", "B", 11)
            pdf.cell(0, 8, f"Issue: {item.get('title', item.get('area', 'Critical Finding'))}", ln=True)
            pdf.set_font("helvetica", "I", 9)
            pdf.cell(0, 5, f"Business Impact: {item.get('impact', 'N/A')}", ln=True)
            pdf.set_font("helvetica", "", 10)
            pdf.multi_cell(0, 5, item.get("paragraph", item.get("issue", "")))
            pdf.ln(3)

        # Roadmap
        pdf.add_page()
        pdf.set_font("helvetica", "B", 16)
        pdf.set_text_color(*self.emerald_color)
        pdf.cell(0, 10, "ENGINEERING EVOLUTION ROADMAP", ln=True)
        
        roadmap = repo_data.get("analysis_results", {}).get("actionable_roadmap", [])
        for i, step in enumerate(roadmap):
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(0, 10, f"PHASE {i+1}: {step.get('title')}", ln=True)
            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(100, 100, 100)
            pdf.multi_cell(0, 5, step.get('detail', step.get('description', '')))
            pdf.ln(4)

        pdf.output(output_path)
